@extends('layouts.master')


      @section('content')
      <div>
      <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Leads</li>
  </ol>
</nav> 
   </div>

   <ol class="breadcrumb bg-light">

       <li> <a href="{{url('registration')}}" class="btn btn-info mb-2" id="create-new-lead">Add Lead</a></li>
    <li><a href="{{url('leads')}}" class="btn btn-secondary mb-2" id="create-new-lead">All Leads</a></li>
    
    </ol>
         <div class="container">
       
         <div class="row">
  
        <div class="col-12">  
            <table class="table table-bordered datatable" id="laravel_datatable">
               <thead class="bg-light">
                  <tr>
                     <th>Client Name</th>
                     <th>Client Email</th>
                     <th>Lead type</th>
                     <th> Generated By</th>
                     <th> Lead Country</th> 
                     <th>Sales Person</th>
                     <th>Recent Comment</th>  
                     <th>Leads Status</th>
                    <th width="280px">Action</th>     
                  </tr>
               </thead>
            </table>
        </div> 
    </div>
</div>


@endsection
@push('script')


  <script type="text/javascript">
  $(function () {
     
      $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
    });
    
    var table =  $('#laravel_datatable').DataTable({
           processing: true,
           serverSide: true,
           ajax: "",
           columns: [    
                    { data: 'clientName', name: 'clientName' },
                    { data: 'clientEmail', name: 'clientEmail' },
                    { data: 'leadType', name: 'leadType' },            
                    { data: 'generatedBy', name: 'generatedBy' },                  
                    { data: 'country', name: 'country' },
                    { data: 'salesPerson', name: 'salesPerson' },
                    { data: 'description', name: 'description' }, 
                    { data: 'leadStatus', name: 'leadStatus' },
                    {data: 'action', name: 'action', orderable: false, searchable: false},            
                 ],order: [[0, 'desc']]
        });

        $('#create-new-lead').click(function () {
        $('#btn-save').val("create-lead");
        $('#leadForm').trigger("reset");

    });

    $('body').on('click', '.edit-lead', function () {
      var lead_id = $(this).data('id');
      $.get('leads/'+lead_id+'/edit', function (data) {
          $('#btn-save').val("edit-lead");
          $('#lead_id').val(data.id);
          $('#title').val(data.title);
          $('#clientName').val(data.clientName);
          $('#clientEmail').val(data.clientEmail); 
          $('#leadType').val(data.description); 
          $('#generatedBy').val(data.generatedBy); 
          $('#country').val(data.country); 
          $('#salesPerson').val(data.salesPerson); 
          $('#description').val(data.description); 
          $('#leadStatus').val(data.leadStatus); 
      })
   });

    $('body').on('click', '.delete-lead', function () {
        var lead_id = $(this).data("id");
        confirm("Are You sure want to delete !");
 
        $.ajax({
            type: "DELETE",
            url: "leads"+'/'+lead_id,
            success: function (data) {
                table.draw();
            },
            error: function (data) {
                console.log('Error:', data);
            }
        });
    }); 

  

});
    if ($("#leadForm").length > 0) {
      $("#leadForm").validate({
     
     submitHandler: function(form) {
        var actionType = $('#btn-save').val();
      $('#btn-save').html('Sending..');
      if(actionType == 'create-lead') {
      $.ajax({
          data: $('#leadForm').serialize(),
          url: "{{ route('leads.add') }}",
          type: "POST",
          dataType: 'json',
          success: function (data) {
            
              $('#leadForm').trigger("reset");
        
              $('#btn-save').html('Save');
              $('.datatable').DataTable().ajax.reload();
          },
          error: function (data) {
              console.log('Error:', data);
              $('#btn-save').html('Save Changes err');
          }
        });
    } 
    else 
    {
        $.ajax({
          data: $('#leadForm').serialize(),
          url: "{{ route('leads.store') }}",
          type: "POST",
          dataType: 'json',
          success: function (data) {   
              $('#leadForm').trigger("reset");
        
              $('#btn-save').html('Save');
              $('.datatable').DataTable().ajax.reload();
          },
          error: function (data) {
              console.log('Error:', data);
              $('#btn-save').html('Save up err');
          }
        });
       }
      }
     })
    }
  </script>
@endpush 