@extends('layouts.master')

@push('meta')
<meta name="csrf-token" content="{{ csrf_token() }}">
@endpush
@push('style')
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"/>
    <style>
    .reg-form {

    }
    
    </style>
@endpush

@section('content')

<div class="reg-form">
    
    <form id="leadForm" name="leadForm">
     <input type="hidden" name="lead_id" id="lead_id">
 
         <div class="form-group">
             <label class="col">Title</label>
               <input type="text" class="form-control" id="title" name="title" value="" required="">
         </div>
        <div class="form-row">
      <div class="form-group col">
        <label for="leadSource">Lead Source</label>
        <select id="leadSource" name="leadSource" class="form-control">
            <option selected>New</option>
            <option>...</option>
          </select>
      </div>
      <div class="form-group col">
        <label for="leadStatus">Lead Status</label>
        <select id="leadStatus" name="leadStatus" class="form-control">
            <option selected>Others</option>
            <option>...</option>
          </select>
      </div>
    </div>
 
    <div class="form-row">
      <div class="form-group col">
        <label for="generatedBy">Generated By</label>
        <select id="generatedBy" name="generatedBy" class="form-control">
            <option selected>Select</option>
            <option>...</option>
          </select>
      </div>
      <div class="form-group col">
        <label for="salesPerson">Sales Person</label>
        <select id="salesPerson" name="salesPerson" class="form-control">
            <option selected>Select</option>
            <option>...</option>
          </select>
      </div>
    </div>
 
     <div class="form-row">
         <div class="form-group col-md-6">
          <label for="clientName ">Client Name</label>
          <input type="text" class="form-control" id="clientName" name="clientName" placeholder="Name">
        </div>
        <div class="form-group col-md-6">
          <label for="clientEmail">Client Email</label>
          <input type="email" class="form-control" id="clientEmail" name ="clientEmail" placeholder="Email">
       </div>  
      </div>
     
      <div class="form-group">
             <label class="col">Description</label>  
           <textarea class="form-control" id="description" name="description" value="" required=""></textarea>
         </div>
      
  
         <div class="form-row">
         <div class="form-group col-md-6">
        <label for="country">Country</label>
        <input type="text" class="form-control" id="country" name ="country">
      </div>
      <div class="form-group col-md-6">
        <label for="phone">Phone No</label>
        <input type="text" class="form-control" id="phone" name ="phone">
      </div>
      </div>
      
 
     
      <div class="form-group">
        <label for="address">Address</label>
        <textarea class="form-control" id="address" name="address"></textarea>
      </div>
 
      
      <div class="form-row">
      <div class="form-group col-md-6">
        <label for="leadtype">Lead Type</label>
        <input type="text" class="form-control" id="leadType" name="leadType">
      </div>
      <div class="form-group col-md-6">
        <label for="organization">Qrganization</label>
        <input type="text" class="form-control" id="organization" name ="organization">
      </div>
      </div>
 
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputCity">City</label>
          <input type="text" class="form-control" id="inputCity">
        </div>
        <div class="form-group col-md-6">
          <label for="state">State</label>
          <input type="text" id="State" name="state" class="form-control">  
        </div>
        
      </div>
      <button type="submit" class="btn btn-primary" id="btn-save" value="create">Save </button>
           
   </form>
   </div>

   @endsection
@push('script')
   <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"></script>

@endpush 